spring.application.name=ticket-booking-api
server.port=8080
spring.datasource.url=jdbc:h2:file:./data/ticketdb;AUTO_SERVER=TRUE
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.h2.console.enabled=true